### ISSUE TITLE
Some Steam games not found in Library or Steam Catalog

### ISSUE THREAD

**Issue by occupanttheory** [gsabater/Steam-Backlog#85] opened 2019-07-11 18:27 UTC
Example: Grim Legends 3: The Dark City. When I filter by names "grim", "grim legends", or any other portion of the name, I do not see the game in my Library or in the Steam Catalog. I have encountered a few games like this, for example "FTL: Faster than Light" and "Stardew Valley". I wasn't sure if it was due to an unreported defect.

**Comment by gsabater** [comment] 2019-07-11 18:48
Hello @occupanttheory 

I have checked and I could find Stardew valley and FTL.
![1](https://user-images.githubusercontent.com/4948172/61076729-2f889d80-a41d-11e9-9d9a-3e9cbe6ebd81.PNG)
![2](https://user-images.githubusercontent.com/4948172/61076733-32838e00-a41d-11e9-8940-1f5104770f01.PNG)


Grim legends 3 is missing for me as well, i'm going to take a look at it.
Appid: 458470
Store: https://store.steampowered.com/app/458470/Grim_Legends_3_The_Dark_City/

**Comment by gsabater** [comment] 2019-07-11 18:49
Oh @occupanttheory , please be sure to have your cache clean. You might want to test again in incognito mode.

Can you give me more information like browser and operating system?

**Comment by occupanttheory** [comment] 2019-07-11 19:55
Thanks, @gsabater! Interesting that they appear for you, but not me! I have tested in incognito mode, but still don't see the games. Screenshots attached, in case they identify something I'm doing wrong.

![image](https://user-images.githubusercontent.com/14241872/61080896-07387900-a3f4-11e9-9131-37006270d048.png)

![image](https://user-images.githubusercontent.com/14241872/61080916-128ba480-a3f4-11e9-8d86-29f0f3265934.png)

Browser info: Chrome Version 75.0.3770.100 (Official Build) (64-bit)

OS info: Windows 10 Pro Version 1803 build 17134.829

**Comment by gsabater** [comment] 2019-07-11 20:08
@occupanttheory 

Thanks for the screenshots. As long as you have chrome you should be good, so no problems here.

Other test you can do are:
- Be sure to order by name, maybe your browser is having issues when processing scores
- Search by appid instead of name. FTL is 212680
- Use a different browser on the same computer ( no need to login), and another device. For example your phone.

Depending on your results we will perform more testing.
Thanks a lot for your feedback, solving this kind of bugs is very important for everyone.

As a note, I happen to find FTL also on my phone
![Screenshot_20190711-220233](https://user-images.githubusercontent.com/4948172/61081812-7039e400-a428-11e9-9db5-b635c7afe4b9.jpg)

**Comment by occupanttheory** [comment] 2019-07-11 21:07
Great suggestions! Here's the results:

1. Filtering by name (not metascore): do not display
2. Another browser on the same machine (**NOT logged in**): **they both show**!
3. Another browser on the same machine (**logged in**): neither of them show!

Which made me want to go back and try:

4. Chrome, but **not logged in**: **they both show**!

So it seems to be something to do with my authenticated app state? Maybe a setting I accidentally toggled?

**Comment by gsabater** [comment] 2019-07-11 21:14
@occupanttheory un glad the testing has been useful!
Definitely looks like it might be something on your user. If you can, please tell me your steam profile, I will look at the database and search for clues.

Also, you might have hidden the games accidentally? 
Yo can go to the backlog tab, and the last button is "hidden apps" go there and see if you have hidden them by mistake. When you open the game modal after clicking over a game, there is a drop-down where you can assign games to any backlog category. One of the categories is "hidden" and maybe you have clicked it by mistake as the drop-down opens on hover.

**Comment by occupanttheory** [comment] 2019-07-11 21:24
Holy cow, that was it. They were just accidentally hidden. So missing games seems to still be a thing (i.e. Grim Legends 3), but far less common than I originally thought!

It sounds like you already have what you need to replicate the Grim Legends 3 issue, but let me know if I can help troubleshoot that! Thanks so much for the tool, it's amazing!

**Comment by gsabater** [comment] 2019-07-12 08:44
@occupanttheory I'm happy to see that was it. I guess you accidentally assigned the hidden status at some point.

If you feel that any interaction could be improved to better understand the website or any other suggestion based on your experience, please, let me know.

About the Grim Legends 3, I already know what happened.
Some months ago I had a bug on the website scraper and some games got flagged as removed from steam. Those games are checked for false positives every six months. As this happened in March, the game should be updated again on September.

Anyway, I have manually updated this game (and a few others that I have detected), and now you should be able to see the game online at https://steam-backlog.com/game/Grim-Legends-3-The-Dark-City

The backlog search filters are updated once a day, so If everything goes as planned, you should be able to search for grim legends 3 tomorrow monrning.

I will keep this issue open until then to be sure that everything is working as intended.

Thanks for everything

**Comment by gsabater** [comment] 2019-07-16 16:41
@occupanttheory 
Hello again. As expected, Grim Legends 3 is now available on the site.
I will close the issue, feel free to open it again or a new one if you find any other problems.

We are also on Discord in case you rather use a chat channel.
https://discord.gg/F2sPE5B

![grim legends](https://user-images.githubusercontent.com/4948172/61312723-4c481b00-a7f9-11e9-89f8-4767a91953d6.PNG)

**Closed by gsabater** 2019-07-16 16:41 UTC
